In [2]:
#instalarea bibliotecii
!pip install numpy

You should consider upgrading via the 'c:\users\clasa215b_nt17\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [3]:
!pip install pandas

You should consider upgrading via the 'c:\users\clasa215b_nt17\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [4]:
!pip install matplotlib

You should consider upgrading via the 'c:\users\clasa215b_nt17\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [5]:
!pip install seaborn

You should consider upgrading via the 'c:\users\clasa215b_nt17\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [6]:
!pip install sklearn

Using legacy setup.py install for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


You should consider upgrading via the 'c:\users\clasa215b_nt17\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [7]:
import numpy  as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('heart.csv')

In [9]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [11]:
# amestecam randurile intre ele
df = df.sample(frac=1)

In [12]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
107   45    0   0       138   236    0        0      152      1      0.2   
87    46    1   1       101   197    1        1      156      0      0.0   
163   38    1   2       138   175    0        1      173      0      0.0   
237   60    1   0       140   293    0        0      170      0      1.2   
252   62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1     37    1   2       130   250    0        1      187      0      3.5   
168   63    1   0       130   254    0        0      147      0      1.4   
297   59    1   0       164   176    1        0       90      0      1.0   
258   62    0   0       150   244    0        1      154      1      1.4   
46    44    1   2       140   235    0        0      180      0      0.0   

     slope  ca  thal  target  
107      1   0     2       1  
87       2   0     3       1  
163      2   4     2       1  
237      1   2     3       0  
252      1   3     2       0  
..     ...  ..   ...     ...  
1        0   0     2       1  
168      1   1     3       0  
297      1   2     1       0  
258      1   0     2       0  
46       2   0     2       1  

[303 rows x 14 columns]

In [14]:
# toate coloanele fara target, axis dupa coloane transformam in matrice
X = df.drop(['target'], axis=1).values
# la fel si pentru y
y =df['target'].values

In [15]:
X

array([[45.,  0.,  0., ...,  1.,  0.,  2.],
       [46.,  1.,  1., ...,  2.,  0.,  3.],
       [38.,  1.,  2., ...,  2.,  4.,  2.],
       ...,
       [59.,  1.,  0., ...,  1.,  2.,  1.],
       [62.,  0.,  0., ...,  1.,  0.,  2.],
       [44.,  1.,  2., ...,  2.,  0.,  2.]])

In [16]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [18]:
knn = KNeighborsClassifier()

In [19]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [20]:
# efectuam predictia
y_pred = knn.predict(X_test)

In [21]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [22]:
#acurracy scor ne permite sa comparam datele reale cu datele prezise de algoritm
accuracy_score(y_pred, y_test)

0.5921052631578947

In [23]:
# marim acuratetea
from sklearn.preprocessing import StandardScaler

In [26]:
std = StandardScaler()
X_train_scaled = std.fit_transform(X_train)

In [27]:
X_test_scaled = std.transform(X_test)

In [28]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [29]:
y_pred = knn.predict(X_test_scaled)

In [30]:
accuracy_score(y_test, y_pred)

0.8026315789473685